# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recipe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recipe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecipe.proto\x12\x07receipt\"&\n\x0eReceiptRequest\x12\x14\n\x0creceiptQuery\x18\x01 \x01(\t\"?\n\x0fReceiptResponse\x12\x17\n\x0fingredientsJson\x18\x01 \x01(\t\x12\x13\n\x0breceiptJson\x18\x02 \x01(\t2W\n\x0eReceiptService\x12\x45\n\x0eGetReceiptInfo\x12\x17.receipt.ReceiptRequest\x1a\x18.receipt.ReceiptResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recipe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIPTREQUEST']._serialized_start=25
  _globals['_RECEIPTREQUEST']._serialized_end=63
  _globals['_RECEIPTRESPONSE']._serialized_start=65
  _globals['_RECEIPTRESPONSE']._serialized_end=128
  _globals['_RECEIPTSERVICE']._serialized_start=130
  _globals['_RECEIPTSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
